### ISSUE TITLE
Could not configure port: (56, 'Invalid request code')

### ISSUE THREAD

**Issue by matthiasbock** [baroobob/TektronixAFG3021B#1]
Hi,

I just cloned your repo and tried to open /dev/usbtmc0, where my Tektronix AFG3102 is attached,
but got the following error:

<pre>
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    open_serial_port()
  File "TektronixAFG3021B.py", line 71, in open_serial_port
    ser.open()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 282, in open
    self._reconfigurePort()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 311, in _reconfigurePort
    raise SerialException("Could not configure port: %s" % msg)
serial.serialutil.SerialException: Could not configure port: (56, 'Invalid request code')
</pre>

The problem occurs in function open_serial_port, the relevant code segment is

<pre>
...
    ser = serial.Serial()
    ser.port = serial_port
    ser.baudrate = 9600
    ser.bytesize = 8
    ser.parity = 'N'
    ser.stopbits = 1
    ser.timeout = None
    ser.xonxoff = 0
    ser.rtscts = 0
    ser.open()
    print ser.is_open()
...
</pre>

I made minor changes, as you can see, but still can't see the problem.

Any idea, what went wrong?

Best, Matthias

**Comment by matthiasbock** [comment]
The code in this repo is ment to run under Windows. Under Linux, the function generator does not register as a serial port but as a "<a href="http://sdpha2.ucsd.edu/Lab_Equip_Manuals/USBTMC_1_00.pdf">USB Test and Measurement Class</a>" device. Instead of using pySerial, the device file (/dev/usbtmc0) can directly be opened and read from/written to, given the usbtmc kernel module is loaded and the user has sufficient permissions for the device file.

See also <a href="https://github.com/duke-87">duke-87</a>'s code: <a href="https://github.com/duke-87/tekusbtmc/blob/master/tekusbtmc.py">tekusbtmc/tekusbtmc.py</a>

**Comment by baroobob** [comment]
Glad you got it sorted out.
